### ISSUE TITLE
Switch to resteasy

### ISSUE THREAD

**Issue by chirino** [syndesisio/syndesis-datamapper#47]
Would be better if we used resteasy instead of Jersey for JAX-RS since thats what syndesis-rest uses.

**Comment by mattrpav** [comment]
@chirino sounds good.  We'll re-wire to     

`<resteasy.version>3.1.1.Final</resteasy.version>`

**Comment by mattrpav** [comment]
Tracking as [AtlasMap #88](https://github.com/atlasmap/atlasmap/issues/88)
