### ISSUE TITLE
Infinite loading when trying to access Data mapper between 2 twitter connectors

### ISSUE THREAD

**Issue by apupier** [syndesisio/syndesis-datamapper#53]
I tried on Crhome and Edge, same result:
![image](https://user-images.githubusercontent.com/1105127/31440483-60cafebc-ae90-11e7-9818-
506fcaf9b52e.png)

I put a twitter connector "mention" as initial step and "Search" as finish step then try to add a step "data mapper"

I found no error in pod logs

**Comment by gashcrumb** [comment]
This issue was moved to atlasmap/atlasmap-ui#102
