### ISSUE TITLE
Search field is not searching in depth in object

### ISSUE THREAD

**Issue by apupier** [syndesisio/syndesis-datamapper#54]
would be best to have a correct search if not possible it would be better to have at least a warning about it saying that the search is incomplete
Having a way to do a full search on demand even if it is taking will be nice.

I hit the issue when trying to follow the getting started searching for the screenName

![image](https://user-images.githubusercontent.com/1105127/31441464-8419ab04-ae93-11e7-90d2-d1364ecbd2bf.png)

**Comment by gashcrumb** [comment]
This issue was moved to atlasmap/atlasmap-ui#103
