### ISSUE TITLE
Provide plain english naming for transformation attributes

### ISSUE THREAD

**Issue by apupier** [syndesisio/syndesis-datamapper#56]
instead of camelcase one for Transformation replace oldString/newString for instance

![image](https://user-images.githubusercontent.com/1105127/31442746-aaeec49a-ae97-11e7-80b7-41380ff7b775.png)

**Comment by gashcrumb** [comment]
@apupier these need to be opened in the atlasmap/atlasmap-ui project...

I'll move the ones you've opened already

**Comment by gashcrumb** [comment]
Hmm, zenhub doesn't let me pick the atlasmap repos

**Comment by gashcrumb** [comment]
This issue was moved to atlasmap/atlasmap-ui#101
